name: generate profile summary card

on:
  schedule:
    - cron: "30 15 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: generate-github-profile-summary-cards
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: "master"
          UTC_OFFSET: 0
          EXCLUDE: ""
          AUTO_PUSH: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
              mv ./profile-summary-card-output/github_dark/0-profile-details.svg ./assets/images/github-profile-details-dark.svg
              mv ./profile-summary-card-output/github_dark/4-productive-time.svg ./assets/images/github-productive-time-dark.svg
              mv ./profile-summary-card-output/github/0-profile-details.svg ./assets/images/github-profile-details.svg
              mv ./profile-summary-card-output/github/4-productive-time.svg ./assets/images/github-productive-time.svg
              git config user.name github-actions
              git config user.email github-actions@github.com
              git add ./assets/images
              git commit -m "Update profile summary card"
              git push
