name: generate snk

on:
  schedule:
    - cron: "30 15 * * *" 
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - uses: actions/checkout@v4
      
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/images/github-snake.svg
            assets/images/github-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: push assets/images dir changes to master 
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes found. Exiting."
            exit 0
          else
            echo "Changes found. Submitting changes to master."
          fi
          
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add ./assets/images
          git commit -m "Update github snake"
          git push
